name: widgetbook_challenge
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+2022070105

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  bloc: ^8.0.3
  bloc_test: ^9.0.3
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_hooks: ^0.18.5+1
  freezed_annotation: ^2.0.3
  test: ^1.21.1

dev_dependencies:
  build_runner: ^2.1.11
  flutter_test:
    sdk: flutter
  freezed: ^2.0.3+1
  mockito: ^5.2.0
  very_good_analysis: ^2.4.0

flutter:
  uses-material-design: true